version: "3"

volumes:
  mysql-data:
    driver: local
  mysql-log:
    driver: local

services:

  mysql-8.0.28:
    image: mysql:8.0.28
    container_name: mysql-8.0.28
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-log:/var/log/mysql
    user: "${CURRENT_UID}"
    command:
      - --max_connections=1000
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}